### ISSUE TITLE
SWCWB: flight issue

### ISSUE THREAD

**Issue by galahadplayer** [Pyrix25633/Forge-StarWarsCloneWars#1]
When playing with other mods that gives player creative flight:

in survival:
The flight provide by the jetpack from this mod will work, but flight provide by other mods such as Coin of Flight or armorplus will be completely disable. 
(Unlike the jetpack from this mod that always gives you flight, other mods need to double tap jump to activate flight like in creative mod. )

in creative:
Everything is normal.

Game version: 1.18.2
forge: 40.2.2

mod used:
Star Wars Clone Wars-1.3.0
Coin of Flight-1.18.2-2.5
armorplus-1.18.2-18.3.0
thedragonlib-1.18.1-1.0.0
geckolib-forge-1.18-3.0.57

**Comment by Pyrix25633** [comment]
I'm sorry, but i cannot fix this at the moment.
